apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s-manifests/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: movies-service
  name: movies-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: movies-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s-manifests/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: movies-service
    spec:
      containers:
        - image: movies-services:1.1
          name: movies-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
